### ISSUE TITLE
Project creation issue when starting eclipse from another directory

### ISSUE THREAD

**Issue by ember91** [opencpi/angryviper_gui#1]
#### Issue description

When eclipse is started from another directory instead of the directory where the binary is located, angryviper project creation won't work.

#### Steps to reproduce the issue

1.  Assuming the eclipse binary is `~/eclipse/eclipse` and the current working directory is `~`,  start eclipse with `./eclipse/eclipse`.
2. Click _Open Perspective_ up to the right in eclipse. Select _ANGRYVIPER Perspective_.
3. Right click in the _OpenCPI Project_ view and select _asset wizard_.
4. Choose _Asset Type_: _Project_, _Project Name_: _Demo_. Click _Finish_.

#### What's the expected result?

The project should show up in the _OpenCPI Project_ view.

#### What's the actual result?

The project doesn't show up in the _OpenCPI Project_ view.

#### Additional details

It seems like the project is created in `~` instead of where it should be created.

My installation:
- eclipse oxygen
- angryviper plugin 1.5
- OpenCPI 1.6.2
- CentOS7

**Comment by opencpi** [comment]
Hi there.
All opencpi issues are tracked on gitlab, not github.
Per the user guide (at opencpi.gitlab.io, section 8), you use the ocpiav command to start this tool.
Feel free to submit an issue at gitlab.com/opencpi/opencpi.
If you are not already subscribed at lists@opencpi.org, you might want to be.

**Comment by ember91** [comment]
Thank you! Using the ocpiav command works better.
